# Generated by Django 5.2.6 on 2025-09-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Excerpt'),
        ),
    ]
