# Generated by Django 5.2.6 on 2025-09-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_postimage_options_alter_tag_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='show_comments',
            field=models.BooleanField(default=True, verbose_name='Show comments'),
        ),
    ]
