from django.conf import settings


# defaults
BLOG_POST_FEATURED = False
BLOG_POST_ALLOW_COMMENTS = True
BLOG_POST_SHOW_COMMENTS = True
BLOG_POST_PUBLISHED = True


BLOG_COMMENT_PUBLISHED = True




if hasattr(settings, "BLOG_POST_FEATURED"):
    BLOG_POST_FEATURED = settings.BLOG_POST_FEATURED


if hasattr(settings, "BLOG_POST_ALLOW_COMMENTS"):
    BLOG_POST_ALLOW_COMMENTS = settings.BLOG_POST_ALLOW_COMMENTS


if hasattr(settings, "BLOG_POST_SHOW_COMMENTS"):
    BLOG_POST_SHOW_COMMENTS = settings.BLOG_POST_SHOW_COMMENTS


if hasattr(settings, "BLOG_POST_PUBLISHED"):
    BLOG_POST_PUBLISHED = settings.BLOG_POST_PUBLISHED




if hasattr(settings, "BLOG_COMMENT_PUBLISHED"):
    BLOG_COMMENT_PUBLISHED = settings.BLOG_COMMENT_PUBLISHED